version: "3.3"
services:
  db:
    image: mongo
    volumes:
      - .docker/data/db:/data/db
    restart: always

  db-ui:
    image: mongo-express
    volumes:
      - .docker/data/db:/data/db
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8081"

  deception-server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
